---
title: "Federal Highway Administration Data Request"
author: "Michael Jensen"
date: "July 2019"
output: html_notebook
---
# Program Description

**Purpose**



**Input(s)**

```{r}
dsn_aws <- "transpAWS"
```

**Output(s)**



# Libraries and Data Sources

```{r}
library(magrittr)
library(odbc)
library(readxl)
library(splitstackshape)
library(tidyverse)

odbc_aws <- dbConnect(odbc::odbc(), dsn_aws)

rm(dsn_aws)

download.file(
  "http://financialreports.utah.gov/chartofaccounts/ChartofAccountFull.xlsx",
  "ucoa.xlsx",
  mode = "wb")
```

# Function Definitions

## Argument Definitions

```{r}

```



# Execution

## UCoA

```{r}
ucoa_fund <- 
  read_xlsx("ucoa.xlsx", sheet = excel_sheets("ucoa.xlsx")[[1]])

ucoa_function <- 
  read_xlsx("ucoa.xlsx", sheet = excel_sheets("ucoa.xlsx")[[2]])

ucoa_account <- 
  read_xlsx("ucoa.xlsx", sheet = excel_sheets("ucoa.xlsx")[[3]])

# Some of the code below will become unnecessary after I edit OSA's Uniform
# Chart of Accounts and publish it on the OSA website.

colnames(ucoa_fund)     <- ucoa_fund[2, ]
colnames(ucoa_function) <- c("NUMBER", ucoa_function[1, 2:4])
colnames(ucoa_account)  <- ucoa_account[2, ]

ucoa_fund     <- ucoa_fund %>% slice(-1, -2)
ucoa_function <- ucoa_function %>% slice(-1)
ucoa_account  <- ucoa_account %>% slice(-1, -2)

extra_fund_numbers <- 
  c(202:298, 302:398, 402:448, 452:498, 502:598, 602:698, 702:798) %>% 
  as.character() %>% 
  enframe(name = NULL) %>% 
  rename("NUMBER" = "value") %>% 
  mutate("SHORT DESCRIPTION" = NA, "FULL DESCRIPTION" = NA, "DETAIL" = NA)

ucoa_fund <- 
  ucoa_fund %>% 
  bind_rows(extra_fund_numbers)

ucoa_fund$NUMBER[[1]]     <- "010"
ucoa_fund$NUMBER[[2]]     <- "020"
ucoa_fund$NUMBER[[3]]     <- "030"
ucoa_function$NUMBER[[1]] <- "000000"

ucoa_account_exp <-
  ucoa_account %>% 
  filter(str_detect(NUMBER, "^4"))

ucoa_account_rev <- 
  ucoa_account %>% 
  filter(str_detect(NUMBER, "^3"))

ucoa <-
  list(
    fund        = ucoa_fund,
    funct       = ucoa_function,
    account     = ucoa_account,
    account_exp = ucoa_account_exp,
    account_rev = ucoa_account_rev)

rm(ucoa_fund, ucoa_function, ucoa_account, extra_fund_numbers, ucoa_account_exp,
   ucoa_account_rev)
```

```{r}
ucoa_transportation <- list()

ucoa_transportation[["funct"]] <- 
  ucoa[["funct"]] %>% 
  filter(
    NUMBER == "000000" | # Not Applicable
    NUMBER == "200000" | # Public Safety
    NUMBER == "200100" | # Administration
    NUMBER == "200403" | # Patrol
    NUMBER == "200406" | # Traffic Control 
    NUMBER == "201200" | # Emergency Management
    NUMBER == "300500" | # Transportation
    NUMBER == "300501" | # Administration
    NUMBER == "300502" | # Streets and Highways
    NUMBER == "300503" | # Sidewalks and Crosswalks
    NUMBER == "300504" | # Maintenance and Testing
    NUMBER == "300505" | # Street Cleaning
    NUMBER == "300506" | # Engineering, Design, and Studies
    NUMBER == "300507" | # Street Lighting and Traffic Controls
    NUMBER == "300508" | # Bridges, Viaducts, and Grade Separations
    NUMBER == "300509" | # Tunnels
    NUMBER == "300700" | # Mass Transit
    NUMBER == "300701" | # Administration
    NUMBER == "300702" | # Operations
    NUMBER == "500316")  # Parkways and Boulevards

ucoa_transportation[["account_rev"]] <- 
  ucoa[["account_rev"]] %>% 
  filter(
    NUMBER == "30010307" | # Mass Transit Tax
    NUMBER == "30010308" | # Transportation Tax
    NUMBER == "30010311" | # Motor Fuels Tax
    NUMBER == "30010312" | # Motor Vehicle Rental Tax
    NUMBER == "30020300" | # Motor Vehicle Registrations
    NUMBER == "30030205" | # Class B and C Road Funds
    NUMBER == "30040203" | # Parking
    NUMBER == "30040207" | # Tolls
    NUMBER == "30050700")  # Parking Fines

ucoa_transportation[["account_exp"]] <- 
  ucoa[["account_exp"]] %>% 
  filter(
    NUMBER == "40050502" | # Road Repair Material
    NUMBER == "40050503")  # Salt and Sand
```

## Transparency

```{r}
entity_table <- 
  dbGetQuery(
    odbc_aws,
    "SELECT id, name, govt_lvl FROM entity")

t_id <- 297 # Beaver County
```

```{r}
transaction_group <- 
  dbGetQuery(
    odbc_aws,
    "SELECT id, name FROM transaction_group")

transportation_rev <- 
  dbGetQuery(
    odbc_aws,
    paste("
          SELECT 
            amount, 
            account_number, 
            description, 
            org1, org2, org3,
            cat1, cat2, cat3,
            fund1, fund2
          FROM transaction
          WHERE fiscal_year = 2018
          AND type = 2
          AND batch_id IN (
            SELECT id
            FROM batch
            WHERE entity_id = ", t_id, "
            AND status = 'PROCESSED')")) %>% 
  cSplit(
    splitCols = "account_number", 
    sep = "-", 
    direction = "wide", 
    type.convert = FALSE) %>% 
  left_join(transaction_group, by = c("org1" = "id")) %>% 
  select(-org1) %>% 
  rename(org1 = name) %>% 
  left_join(transaction_group, by = c("org2" = "id")) %>% 
  select(-org2) %>% 
  rename(org2 = name) %>% 
  left_join(transaction_group, by = c("org3" = "id")) %>% 
  select(-org3) %>% 
  rename(org3 = name) %>% 
  left_join(transaction_group, by = c("cat1" = "id")) %>% 
  select(-cat1) %>% 
  rename(cat1 = name) %>% 
  left_join(transaction_group, by = c("cat2" = "id")) %>% 
  select(-cat2) %>% 
  rename(cat2 = name) %>% 
  left_join(transaction_group, by = c("cat3" = "id")) %>% 
  select(-cat3) %>% 
  rename(cat3 = name) %>% 
  left_join(transaction_group, by = c("fund1" = "id")) %>% 
  select(-fund1) %>% 
  rename(fund1 = name) %>% 
  left_join(transaction_group, by = c("fund2" = "id")) %>% 
  select(-fund2) %>% 
  rename(fund2 = name)
  # filter(account_number_2 %in% ucoa_transportation[["funct"]]$NUMBER)

transportation_exp <- 
  dbGetQuery(
    odbc_aws,
    paste("
          SELECT 
            amount, 
            account_number, 
            description, 
            org1, org2, org3,
            cat1, cat2, cat3,
            fund1, fund2
          FROM transaction
          WHERE fiscal_year = 2018
          AND type = 1
          AND batch_id IN (
            SELECT id
            FROM batch
            WHERE entity_id = ", t_id, "
            AND status = 'PROCESSED')")) %>% 
  cSplit(
    splitCols = "account_number", 
    sep = "-", 
    direction = "wide", 
    type.convert = FALSE) %>% 
  left_join(transaction_group, by = c("org1" = "id")) %>% 
  select(-org1) %>% 
  rename(org1 = name) %>% 
  left_join(transaction_group, by = c("org2" = "id")) %>% 
  select(-org2) %>% 
  rename(org2 = name) %>% 
  left_join(transaction_group, by = c("org3" = "id")) %>% 
  select(-org3) %>% 
  rename(org3 = name) %>% 
  left_join(transaction_group, by = c("cat1" = "id")) %>% 
  select(-cat1) %>% 
  rename(cat1 = name) %>% 
  left_join(transaction_group, by = c("cat2" = "id")) %>% 
  select(-cat2) %>% 
  rename(cat2 = name) %>% 
  left_join(transaction_group, by = c("cat3" = "id")) %>% 
  select(-cat3) %>% 
  rename(cat3 = name) %>% 
  left_join(transaction_group, by = c("fund1" = "id")) %>% 
  select(-fund1) %>% 
  rename(fund1 = name) %>% 
  left_join(transaction_group, by = c("fund2" = "id")) %>% 
  select(-fund2) %>% 
  rename(fund2 = name)
  # filter(account_number_2 %in% ucoa_transportation[["funct"]]$NUMBER)

unique_values <- list()

unique_values$rev <- 
  as.list(
unique_rev_descriptions <- transportation_rev$org1 %>% unique() %>% as.matrix(),
unique_rev_org1  <- transportation_rev$org1  %>% unique() %>% as.matrix(),
unique_rev_org2  <- transportation_rev$org2  %>% unique() %>% as.matrix(),
unique_rev_org3  <- transportation_rev$org3  %>% unique() %>% as.matrix(),
unique_rev_cat1  <- transportation_rev$cat1  %>% unique() %>% as.matrix(),
unique_rev_cat2  <- transportation_rev$cat2  %>% unique() %>% as.matrix(),
unique_rev_cat3  <- transportation_rev$cat3  %>% unique() %>% as.matrix(),
unique_rev_fund1 <- transportation_rev$fund1 %>% unique() %>% as.matrix(),
unique_rev_fund2 <- transportation_rev$fund2 %>% unique() %>% as.matrix())

unique_values$exp <- 
  as.list(
unique_exp_descriptions <- transportation_exp$org1 %>% unique() %>% as.matrix(),
unique_exp_org1  <- transportation_exp$org1  %>% unique() %>% as.matrix(),
unique_exp_org2  <- transportation_exp$org2  %>% unique() %>% as.matrix(),
unique_exp_org3  <- transportation_exp$org3  %>% unique() %>% as.matrix(),
unique_exp_cat1  <- transportation_exp$cat1  %>% unique() %>% as.matrix(),
unique_exp_cat2  <- transportation_exp$cat2  %>% unique() %>% as.matrix(),
unique_exp_cat3  <- transportation_exp$cat3  %>% unique() %>% as.matrix(),
unique_exp_fund1 <- transportation_exp$fund1 %>% unique() %>% as.matrix(),
unique_exp_fund2 <- transportation_exp$fund2 %>% unique() %>% as.matrix())

```

Highland:

```{r}
highland_exp <- 
  dbGetQuery(
    odbc_aws,
    paste("
          SELECT account_number
          FROM transaction
          WHERE batch_id IN (
            SELECT id
            FROM batch
            WHERE entity_id = 445
            AND status IN ('PROCESSED', 'PROCESSING', 'DONTDELETE'))
          AND type = 1")) 
  # .[["account_number"]]
  
unique_highland_exp <-   
  unique(highland_exp$account_number) %>% 
  as_tibble()
```

# DBMS Disconnection

```{r}
dbDisconnect(odbc_aws)
```