---
title: "Tabiona Town & Smuin, Rich, & Marsing"
author: "Michael Jensen"
date: "February 2018"
output: html_notebook
---
# Program Description

**Purpose**



**Input(s)**



**Output(s)**



# Libraries and Data Source(s)

```{r}
library(odbc)
library(tidyverse)

odbc_aws <- dbConnect(odbc::odbc(), "transpAWS")
```

#  Function Definitions



# Execution

```{sql, connection=odbc_aws, output.var=entity_table}
SELECT *
FROM entity
WHERE name LIKE "Tabiona%"
```

```{sql, connection=odbc_aws, output.var=vendor_table}
SELECT *
FROM vendor
WHERE entity_id = 1337
AND lower(name) LIKE "%smuin%"
```

```{sql, connection=odbc_aws, output.var=vendor_summary_table}
SELECT *
FROM vendor_summary
WHERE vendor_id = 5537643
```

```{sql, connection=odbc_aws, output.var=vendor_smuin}
SELECT 
  vendor.id AS vendor_id,
  vendor.name AS vendor_name,
  vendor_summary.type AS transaction_type,
  vendor_summary.fiscal_year,
  vendor_summary.total,
  vendor_summary.count
FROM vendor
JOIN vendor_summary
ON vendor.id = vendor_summary.vendor_id
WHERE vendor.entity_id = 1337
AND lower(vendor.name) LIKE "%smuin%"
```

# DBMS Disconnection

```{r}
dbDisconnect(odbc_aws)
```